name: Build Linux
on:
  push:
    branches:
      - run-actions
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies on Linux
        run: |
          sudo apt update
          sudo apt install llvm-dev libwayland-dev libxkbcommon-dev libx11-xcb-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev liblldb-dev libgl1-mesa-dev
        shell: bash

      - name: Build Package on Linux
        run: |
          cmake -G Ninja -B build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -DCMAKE_VERBOSE_MAKEFILE=ON
          cmake --build build --config Debug
          cpack --config build/CPackConfig.cmake
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lldb-frontend-linux
          path: lldb-frontend-linux.tar.gz